/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algo1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import algo1.BddAlgoBreizh;


/**
 *
 * @author ebent
 */
public class ConsulterClient extends javax.swing.JFrame {
    
    Statement st;
    PreparedStatement pstmt;
    /**
     * Creates new form ConsulterClient
     */
    public ConsulterClient() {
        initComponents();
        table_update();
    }
    
    private void table_update(){
        int c;
        try{ 
           
                
                String sql=("select * from clients");
                
                BddAlgoBreizh bdd = new BddAlgoBreizh();
                st= (Statement) bdd.conn.createStatement();
                pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);
                

                ResultSet rs= pstmt.executeQuery();
                ResultSetMetaData Rss = (ResultSetMetaData) rs.getMetaData();
                c= Rss.getColumnCount();
                
                DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
                tm.setRowCount(0);
                while(rs.next()){
                Object o[]={rs.getInt("IdClient"),rs.getString("Entreprise"),rs.getString("Nom"),rs.getString("Prenom"),rs.getString("Adresse"),
                    rs.getString("CodePostale"),rs.getString("Ville"),rs.getString("TelephoneMobile"),rs.getString("TelephoneFixe")};
                tm.addRow(o);
                }
                 }catch(Exception e){
                     JOptionPane.showMessageDialog(null,e);
                 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameAjoutRDV = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        cdernierev = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewClient = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        cplanif = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtentreprise = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JLabel();
        txtadress = new javax.swing.JLabel();
        txtccp = new javax.swing.JLabel();
        txtville = new javax.swing.JLabel();
        txtmobile = new javax.swing.JLabel();
        txtfixe = new javax.swing.JLabel();
        ce = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        cpr = new javax.swing.JTextField();
        ca = new javax.swing.JTextField();
        ccp = new javax.swing.JTextField();
        cv = new javax.swing.JTextField();
        ctm = new javax.swing.JTextField();
        ctf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrameAjoutRDVLayout = new javax.swing.GroupLayout(jFrameAjoutRDV.getContentPane());
        jFrameAjoutRDV.getContentPane().setLayout(jFrameAjoutRDVLayout);
        jFrameAjoutRDVLayout.setHorizontalGroup(
            jFrameAjoutRDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrameAjoutRDVLayout.setVerticalGroup(
            jFrameAjoutRDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cdernierev.setBackground(new java.awt.Color(153, 153, 153));
        cdernierev.setForeground(new java.awt.Color(0, 51, 153));
        cdernierev.setText("Dernières visites");
        cdernierev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdernierevActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultation clients");

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setForeground(new java.awt.Color(0, 51, 153));
        jButton7.setText("Actualiser");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        viewClient.setBackground(new java.awt.Color(102, 153, 255));
        viewClient.setForeground(new java.awt.Color(0, 0, 153));
        viewClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Client", "Entreprise", "Nom", "Prénom", "Adresse", "CodePostale", "Ville", "Mobile", "Fixe", "Date "
            }
        ));
        viewClient.setShowGrid(true);
        viewClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(viewClient);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setForeground(new java.awt.Color(0, 51, 153));
        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cplanif.setBackground(new java.awt.Color(153, 153, 153));
        cplanif.setForeground(new java.awt.Color(0, 51, 153));
        cplanif.setText("Planifier");
        cplanif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cplanifActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter un client");

        txtentreprise.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtentreprise.setForeground(new java.awt.Color(255, 255, 255));
        txtentreprise.setText("Entreprise:");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setText("Nom:");

        txtlastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(255, 255, 255));
        txtlastname.setText("Prénom:");

        txtadress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtadress.setForeground(new java.awt.Color(255, 255, 255));
        txtadress.setText("Adresse:");

        txtccp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtccp.setForeground(new java.awt.Color(255, 255, 255));
        txtccp.setText("Code Postale:");

        txtville.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtville.setForeground(new java.awt.Color(255, 255, 255));
        txtville.setText("Ville:");

        txtmobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtmobile.setForeground(new java.awt.Color(255, 255, 255));
        txtmobile.setText("Téléphone Mobile:");

        txtfixe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfixe.setForeground(new java.awt.Color(255, 255, 255));
        txtfixe.setText("Téléphone Fixe:");

        ccp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccpKeyTyped(evt);
            }
        });

        ctm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctmKeyTyped(evt);
            }
        });

        ctf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctfKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Ajouter un client");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtentreprise)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpr, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmobile)
                            .addComponent(txtville)
                            .addComponent(txtadress)
                            .addComponent(txtlastname)
                            .addComponent(txtfixe)
                            .addComponent(txtccp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ccp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(75, 75, 75)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cv, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctm, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtentreprise)
                    .addComponent(ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlastname)
                    .addComponent(cpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtadress)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtccp)
                    .addComponent(ccp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtville)
                    .addComponent(cv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmobile)
                    .addComponent(ctm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfixe)
                    .addComponent(ctf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(0, 51, 153));
        jButton6.setText("Se déconnecter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(cdernierev, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cplanif, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cdernierev))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(523, 523, 523)
                            .addComponent(cplanif, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(584, 584, 584)
                            .addComponent(jButton6))
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(550, 550, 550))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(cdernierev))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(cplanif)
                    .addComponent(jButton6))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
        int selectedIndex = viewClient.getSelectedRow();
        
        
        try{ 
            int idClient = Integer.parseInt(tm.getValueAt(selectedIndex, 0).toString());
            String entreprise = ce.getText();
            String nom = cn.getText();
            String prenom = cpr.getText();
            String adresse = ca.getText();
            String codePostale = ccp.getText();
            String ville = cv.getText();
            String mobile = ctm.getText();
            String fixe = ctf.getText();
            
            String sql = ("update clients SET  Entreprise=?,Nom=?,Prenom=?,Adresse=?,CodePostale=?,Ville=?,TelephoneMobile=?,TelephoneFixe=? WHERE idClient=?");

            BddAlgoBreizh bdd = new BddAlgoBreizh();
            st= (Statement) bdd.conn.createStatement();
            pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);

     
            pstmt.setString(1, entreprise);
            pstmt.setString(2, nom);
            pstmt.setString(3, prenom);
            pstmt.setString(4, adresse);
            pstmt.setString(5, codePostale);
            pstmt.setString(6, ville);
            pstmt.setString(7, mobile);
            pstmt.setString(8, fixe);
            pstmt.setInt(9, idClient);
            pstmt.executeUpdate();
            
        
             JOptionPane.showMessageDialog(this, "Les informations du client ont été modifiés!");
             
             ce.setText("");cn.setText("");cpr.setText("");ca.setText("");ccp.setText("");cv.setText("");ctm.setText("");ctf.setText("");
             //ce.requestFocus();
        
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        welcome obj = new welcome();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginPage obj = new LoginPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            //System.out.println("insert into clients values (?,?,?,?,?,?,?,?)");
            if(ce.getText().length()!=0 && cn.getText().length()!=0 && cpr.getText().length()!=0 && ca.getText().length()!=0 && ccp.getText().length()!=0 && 
                    cv.getText().length()!=0 && ctm.getText().length()!=0 && ctf.getText().length()!=0 ){

                String sql = "INSERT INTO CLIENTS (entreprise,nom,prenom,adresse,codepostale,ville,telephonemobile,telephonefixe) VALUES (?,?,?,?,?,?,?,?)";    
                BddAlgoBreizh bdd = new BddAlgoBreizh();
                st= (Statement) bdd.conn.createStatement();
                pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);

                
                //ptstmt.setString(1, cid.getText());
                pstmt.setString(1, ce.getText());
                pstmt.setString(2, cn.getText());
                pstmt.setString(3, cpr.getText());
                pstmt.setString(4, ca.getText());
                pstmt.setString(5, ccp.getText());
                pstmt.setString(6, cv.getText());
                pstmt.setString(7, ctm.getText());
                pstmt.setString(8, ctf.getText());
                pstmt.executeUpdate();
                //conn.close();
                JOptionPane.showMessageDialog(null, "Client ajouté avec succès!");
                table_update();
            }
            else{
                JOptionPane.showMessageDialog(null, "Tous les champs doivent être completé");
            }
            
           
        
        
            //cid.setText("");
            ce.setText("");cn.setText("");cpr.setText("");ca.setText("");ccp.setText("");cv.setText("");ctm.setText("");ctf.setText("");
            ce.requestFocus();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{ Class.forName("com.mysql.jdbc.Driver");
        
        
                String sql="select * from clients";
                BddAlgoBreizh bdd = new BddAlgoBreizh();
                st= (Statement) bdd.conn.createStatement();
                pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);
        
                ResultSet rs= pstmt.executeQuery();
                DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
                tm.setRowCount(0);
                while(rs.next()){
                Object o[]={rs.getInt("IdClient"),rs.getString("Entreprise"),rs.getString("Nom"),rs.getString("Prenom"),rs.getString("Adresse"),
                    rs.getString("CodePostale"),rs.getString("Ville"),rs.getString("TelephoneMobile"),rs.getString("TelephoneFixe")};
                tm.addRow(o);
                table_update();
                }
                 }catch(Exception e){
                     JOptionPane.showMessageDialog(null,e);
                 }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void viewClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewClientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
        int selectedIndex = viewClient.getSelectedRow();
        
        ce.setText(tm.getValueAt(selectedIndex, 1).toString());
        cn.setText(tm.getValueAt(selectedIndex, 2).toString());
        cpr.setText(tm.getValueAt(selectedIndex, 3).toString());
        ca.setText(tm.getValueAt(selectedIndex, 4).toString());
        ccp.setText(tm.getValueAt(selectedIndex, 5).toString());
        cv.setText(tm.getValueAt(selectedIndex, 6).toString());
        ctm.setText(tm.getValueAt(selectedIndex, 7).toString());
        ctf.setText(tm.getValueAt(selectedIndex, 8).toString());
        
        
    }//GEN-LAST:event_viewClientMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
        int selectedIndex = viewClient.getSelectedRow();
        
         try{ 
            int idClient = Integer.parseInt(tm.getValueAt(selectedIndex, 0).toString());
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer le client sélectionné?","Avertissement",JOptionPane.YES_NO_OPTION);
            
            if(dialogResult == JOptionPane.YES_OPTION){
                
            String sql = ("delete FROM clients WHERE idClient=?");
            BddAlgoBreizh bdd = new BddAlgoBreizh();
            st= (Statement) bdd.conn.createStatement();
            pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);

            
       
            pstmt.setInt(1, idClient);
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Le client n°" +idClient+" a été supprimé!");
            table_update();
             
             ce.setText("");cn.setText("");cpr.setText("");ca.setText("");ccp.setText("");cv.setText("");ctm.setText("");ctf.setText("");
             ce.requestFocus();
            
            }
            
            
            
            
            
        
             
        
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ctmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctmKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
        }
    }//GEN-LAST:event_ctmKeyTyped

    private void ctfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctfKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
        }
    }//GEN-LAST:event_ctfKeyTyped

    private void ccpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccpKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
        }
    }//GEN-LAST:event_ccpKeyTyped

    private void cplanifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cplanifActionPerformed
        // TODO add your handling code here:
         //jFrameAjoutRDV = new jFrameAjoutRDV();
        //obj.setVisible(true);
        //dispose();
        
    }//GEN-LAST:event_cplanifActionPerformed

    private void cdernierevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdernierevActionPerformed
        // TODO add your handling code here:
        try{
            
                String sql="SELECT visites_rdv.Date, visites_rdv.idClient,clients.idClient,clients.Entreprise,clients.Nom,clients.Prenom,clients.Adresse,clients.CodePostale,clients.Ville,clients.TelephoneMobile,clients.TelephoneFixe FROM clients LEFT JOIN visites_rdv ON visites_rdv.idClient = clients.idClient ORDER BY Date";
                BddAlgoBreizh bdd = new BddAlgoBreizh();
                st= (Statement) bdd.conn.createStatement();
                pstmt=(PreparedStatement) bdd.conn.prepareStatement(sql);
            
                ResultSet rs= pstmt.executeQuery();
                DefaultTableModel tm=(DefaultTableModel)viewClient.getModel();
                tm.setRowCount(0);
                while(rs.next()){
                    
                String visite_data_rdv = rs.getString("visites_rdv.Date");
                
                if(visite_data_rdv == null){
                    visite_data_rdv = "Aucun";
                }
                
                Object o[]={rs.getInt("clients.idClient"),rs.getString("Entreprise"),rs.getString("Nom"),rs.getString("Prenom"),rs.getString("Adresse"),
                    rs.getString("CodePostale"),rs.getString("Ville"),rs.getString("TelephoneMobile"),rs.getString("TelephoneFixe"),visite_data_rdv};
                tm.addRow(o);
                //table_update();
                }
                 }catch(Exception e){
                     JOptionPane.showMessageDialog(null,e);
                 }
    }//GEN-LAST:event_cdernierevActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsulterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsulterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsulterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsulterClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsulterClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca;
    private javax.swing.JTextField ccp;
    private javax.swing.JButton cdernierev;
    private javax.swing.JTextField ce;
    private javax.swing.JTextField cn;
    private javax.swing.JButton cplanif;
    private javax.swing.JTextField cpr;
    private javax.swing.JTextField ctf;
    private javax.swing.JTextField ctm;
    private javax.swing.JTextField cv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrameAjoutRDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtadress;
    private javax.swing.JLabel txtccp;
    private javax.swing.JLabel txtentreprise;
    private javax.swing.JLabel txtfixe;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtmobile;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtville;
    private javax.swing.JTable viewClient;
    // End of variables declaration//GEN-END:variables
}
